
services:
  mysql:
    image: mysql:8.0 # Puedes cambiar la versión según lo necesites
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"  # Exponer el puerto 3306 de MySQL al host
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen para persistencia de datos
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
    - backend/.env.python
    - .env
    networks:
      - backend_network
    volumes:
      - ./backend/app/static:/app/app/static

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
